version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Passw@rd123
      MYSQL_DATABASE: hstudy
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  server:
    image: quochung5c/hstudy-server:1.0
    container_name: server_container
    depends_on:
      - db
    ports:
      - 8080:8080
